### ISSUE TITLE
Need Tanganika chainspec with bootnodes

### ISSUE THREAD

**Issue by sourabhniyogi** [DataHighway-DHX/DataHighway-Parachain#41]
Can you post a link the Tanganika [Kusama paraID 2116] chainspec -- with the bootnodes included? We [Polkaholic.io] are building a multi-chain block explorer with XCM support cf
https://tanganika.polkaholic.io/chain/tanganika
and are attempting to run a full archive node (to index blocks including traces, xcm transfers into and out of Tanganika, etc.) and couldn't find the chainspec/bootnodes in your repo to do so.

**Comment by ayushmishra2005** [comment]
You can find raw spec here https://github.com/DataHighway-DHX/DataHighway-Parachain/blob/v3.6.0/res/kusama/kusama-parachain-raw.json. For bootnote related information, request this from DHX team through Discord
